#!/bin/bash
# vim: set ft=sh

set -e -u -x

export TMPDIR=/tmp
export GOPATH=$HOME/workspace/golang
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/../built-resource

cd $GOPATH/src/github.com/concourse/pool-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

cp -R test/ assets/ Dockerfile $BUILD_DIR
GOOS=linux go build -o $BUILD_DIR/built-out ./cmd/out

